baseURL: https://docs.circonus.com/
languageCode: en-us
title: Circonus Documentation
canonifyURLs: true

disableKinds: ["RSS"]

deployment:
  targets:
    name: docs.circonus.com
    URL: gs://docs.circonus.com

menu:
  products:

  - identifier: circonus users
    name: Circonus Users
    pre: <i class='far fa-window super-icon'></i>
    post: Usage of the Circonus SaaS platform
    url: /circonus-users/
    weight: 10

  - identifier: circonus on-premises
    name: Circonus On-Premises
    pre: <i class='far fa-server super-icon'></i>
    post: Installation and usage of Circonus on-premises 
    url: /circonus-on-premises/
    weight: 20

  - identifier: irondb
    name: IRONdb
    pre: <i class='far fa-database super-icon'></i>
    post: Our fault-tolerant, time series database
    url: /irondb/
    weight: 30

  - identifier: caql
    name: CAQL
    pre: <i class='far fa-brackets-curly super-icon'></i>
    post: Circonus Analytics Query Language
    url: /caql/
    weight: 40
